version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
  app:
    build:
      context: .
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
